The formal proposal.
UICHCC/HCC-Regulations pull request #7
Opened 2018-04-16 08:53 UTC by billzhonggz

Here is the formal proposal to Innovation Centre. Please review the Chinese version first and the English version will be here soon.
**DO NOT MERGE UNTIL I DO THIS**

2018-04-22 09:46 UTC, lzcapp requested changes
拥有**学生组织的身份**即有**行政事务的支持**，是不是可以不用单独写出？

2018-04-22 09:53 UTC, ecwu approved these changes

2018-04-22 10:04 UTC, ecwu commented
@RainySummerLuo 如果我们是向 SAO 申请学生社团，我们便不用刻意提到行政相关支持，因为 SAO 对学生社团能提供的行政支持已经有规章制度写明。
但是我们是向 IC 提交的申请。IC 作为一个还未完全落地的新部门（组织），很多规章还未完善。所以我觉得在这里提出需要行政事务的支持并不是毫无意义的。

2018-04-23 07:36 UTC, DRJ31 approved these changes

2018-04-24 02:22 UTC, jyhi commented
@RainySummerLuo If you agree with @ecwu please approve the changes.

2018-04-28 16:23 UTC, merged